site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Default:index }

site_unsere_kanzlei:
    path:     /kanzlei
    defaults: { _controller: SiteBundle:Default:kanzlei }

sekretariat:
    path:     /kanzlei/sekretariat
    defaults: { _controller: SiteBundle:Default:sekretariat }

sprechzeiten:
    path:     /kanzlei/sprechzeiten
    defaults: { _controller: SiteBundle:Default:sprechzeiten }

anfahrt:
    path:     /kanzlei/anfahrt
    defaults: { _controller: SiteBundle:Default:anfahrt }

anwaelte:
    path:     /anwaelte
    defaults: { _controller: SiteBundle:Default:anwalt }

lutzEisel:
    path:     /lutz-eisel
    defaults: { _controller: SiteBundle:Default:lutzEisel }

evaKarrmann:
    path:     /eva-karrmann
    defaults: { _controller: SiteBundle:Default:evaKarrmann }

tobiasReimann:
    path:     /tobias-reimann
    defaults: { _controller: SiteBundle:Default:tobiasReimann }

manifest:
    path:     /manifest
    defaults: { _controller: SiteBundle:Default:manifest }

rechtsgebiete:
    path:     /rechtsgebiete
    defaults: { _controller: SiteBundle:Default:rechtsgebiete }

strafrecht:
    path:     /strafrecht
    defaults: { _controller: SiteBundle:Default:strafrecht }

strafrecht-uebersicht:
    path:     /uebersicht-strafrecht
    defaults: { _controller: SiteBundle:Default:strafrechtUebersicht }
