site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Default:index }

site_unsere_kanzlei:
    path:     /kanzlei
    defaults: { _controller: SiteBundle:Default:kanzlei }

sekretariat:
    path:     /kanzlei/sekretariat
    defaults: { _controller: SiteBundle:Default:sekretariat }

sprechzeiten:
    path:     /kanzlei/sprechzeiten
    defaults: { _controller: SiteBundle:Default:sprechzeiten }

anfahrt:
    path:     /kanzlei/anfahrt
    defaults: { _controller: SiteBundle:Default:anfahrt }

anwaelte:
    path:     /anwaelte
    defaults: { _controller: SiteBundle:Default:anwalt }

lutzEisel:
    path:     /lutz-eisel
    defaults: { _controller: SiteBundle:Default:lutzEisel }

evaKarrmann:
    path:     /eva-karrmann
    defaults: { _controller: SiteBundle:Default:evaKarrmann }

tobiasReimann:
    path:     /tobias-reimann
    defaults: { _controller: SiteBundle:Default:tobiasReimann }

manifest:
    path:     /manifest
    defaults: { _controller: SiteBundle:Default:manifest }

rechtsgebiete:
    path:     /rechtsgebiete
    defaults: { _controller: SiteBundle:Default:rechtsgebiete }

strafrecht:
    path:     /strafrecht
    defaults: { _controller: SiteBundle:Default:strafrecht }

strafrecht-uebersicht:
    path:     /uebersicht-strafrecht
    defaults: { _controller: SiteBundle:Default:strafrechtUebersicht }

strafverfahren:
    path:     /strafverfahren
    defaults: { _controller: SiteBundle:Default:strafverfahren }

pflichtverteidigung:
    path:     /pflichtverteidigung
    defaults: { _controller: SiteBundle:Default:pflichtverteidigung }

bussgeldsachen:
    path:     /bussgeldsachen
    defaults: { _controller: SiteBundle:Default:bussgeld }

polizei-ordnungsrecht:
    path:     /polizeirecht-ordnungsrecht
    defaults: { _controller: SiteBundle:Default:polizei }

psychiatrie:
    path:     /psychiatrie
    defaults: { _controller: SiteBundle:Default:psychiatrie }

familienrecht:
    path:     /familienrecht
    defaults: { _controller: SiteBundle:Default:familienrecht }

verkehrsrecht:
    path:     /verkehrsrecht
    defaults: { _controller: SiteBundle:Default:verkehrsrecht }

zivilrecht:
    path:     /zivilrecht
    defaults: { _controller: SiteBundle:Default:zivilrecht }

vertragsrecht:
    path:     /vertragsrecht
    defaults: { _controller: SiteBundle:Default:vertragsrecht }

arbeitsrecht:
    path:     /arbeitsrecht
    defaults: { _controller: SiteBundle:Default:arbeitsrecht }

erbrecht:
    path:     /erbrecht
    defaults: { _controller: SiteBundle:Default:erbrecht }

mietrecht:
    path:     /mietrecht
    defaults: { _controller: SiteBundle:Default:mietrecht }

notar:
    path:     /notar
    defaults: { _controller: SiteBundle:Default:notar }

aktuelles:
    path:     /aktuelles
    defaults: { _controller: SiteBundle:Default:aktuelles }

rechtsprechung:
    path:     /aktuelles/rechtsprechung
    defaults: { _controller: SiteBundle:Default:rechtsprechung }

kosten:
    path:     /kosten
    defaults: { _controller: SiteBundle:Default:kosten }

notdienst:
    path:     /notdienst
    defaults: { _controller: SiteBundle:Default:notdienst }

links:
    path:     /links
    defaults: { _controller: SiteBundle:Default:links }
